services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
    env_file:
      - ${HOME}/secrets/.env
    volumes:
      - $HOME/vpn-servers:/gluetun
      - $HOME/secrets:/secrets
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=openvpn
      - TZ=America/New_York
      - SERVER_COUNTRIES=United States,Canada,Netherlands,Germany
      - SERVER_CITIES=Dallas,Houston,Chicago,New York,Los Angeles,Toronto,Amsterdam,Berlin
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=6h
      - HTTPPROXY=on  # Ensure the HTTP proxy is enabled
    networks:
      - server_setup_internal-net  # Connect to the same network as other containers
    healthcheck:
      test: [ "CMD", "pgrep", "openvpn" ]  # Example health check using OpenVPN process status
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  server_setup_internal-net:
    external: true  # Ensure the network is external and shared
