FROM python:3.9-slim

WORKDIR /app

COPY app.py /app
COPY common /app/common

RUN pip install flask psutil docker flask-restx flask-cors

# Install git and docker-compose
RUN apt-get update && apt-get install -y git curl
RUN apt-get update && apt-get install -y ffmpeg
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

CMD ["python", "app.py"]
