services:
  vpn-proxy:
    build:
      context: .
      dockerfile: Dockerfile.vpn
    ports:
      - "8002:8002"
    image: vpn_setup:v1.4
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - $HOME/vpn-servers/cong:/vpn-servers
      - $HOME/secrets:/secrets
    networks:
      - server_setup_internal-net

networks:
  server_setup_internal-net:
    external: true
