FROM mariadb:10.5

# Copy initialization scripts
COPY init.template.sql /docker-entrypoint-initdb.d/
COPY init.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init.sh

# Ensure that /docker-entrypoint-initdb.d/ is writable
RUN chmod 777 /docker-entrypoint-initdb.d

# Define the default command
CMD ["mysqld"]
