services:
  vpn-proxy:
    build:
      context: .
      dockerfile: Dockerfile.vpn
    ports:
      - "8002:8002"
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - $HOME/vpn-servers:/vpn-servers
      - $HOME//secrets/surfshark_credentials.txt:/secrets/surfshark_credentials.txt
    environment:
      - TINYPROXY_PORT=8002
