version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    env_file:
      - /home/secrets/.env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  server_setup:
    build: .
    container_name: server_setup
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/secrets/.env:/home/secrets/.env  # Mount the .env file
      - /home/redbull:/home/redbull            # Mount the /home/redbull directory
    ports:
      - "5000:5000"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/docker-volumes/mariadb
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/docker-volumes/redis
