FROM mariadb:10.6

# Copy initialization scripts
COPY init.template.sql /docker-entrypoint-initdb.d/
COPY init.sh /docker-entrypoint-initdb.d/

# Debug: List files and permissions
RUN ls -l /docker-entrypoint-initdb.d/

# Set permissions
RUN chmod +x /docker-entrypoint-initdb.d/init.sh
RUN chmod 777 /docker-entrypoint-initdb.d/init.sh

# Debug: List files and permissions again
RUN ls -l /docker-entrypoint-initdb.d/

# Define the default command
CMD ["mysqld"]
