services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "source ${HOME}/secrets/.env && mysqladmin ping -h localhost -u $MYSQL_USER -p$MYSQL_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - ${HOME}/secrets/.env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql file
    ports:
      - "3306:3306"
    networks:
      - internal-net

  redis:
    image: redis:6
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - internal-net

  server_setup:
    build: .
    container_name: server_setup
    restart: always
    depends_on:
      - mariadb
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}:/home/redbull
      - /:/host_fs  # Add this line to bind mount the host root
    ports:
      - "5000:5000"
    networks:
      - internal-net

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/docker-volumes/mariadb
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/docker-volumes/redis

networks:
  internal-net:
    driver: bridge